# Loaded for interactive shells.

# Prepend startup functions path and remove duplicates.
typeset -Ua fpath

export PATH="/usr/local/opt/node@12/bin:$PATH"

eval "$(starship init zsh)"

# vim: set ft=zsh ts=2 sw=2 et:

